[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

hook_add="""
let g:go_def_mode='gopls'
let g:go_info_mode='gopls'
let g:go_fmt_command = 'goimports'
let g:go_metalinter_enabled = []
let g:go_metalinter_autosave_enabled = []
"""



