[[plugins]]
repo = 'Shougo/dein.vim'
rtp = ''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd']

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  source ~/.vim/rc/plugins/lightline.vim
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'nnoremap <silent><C-e> :NERDTreeToggle<CR>'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'thinca/vim-ft-diff_fold'
on_ft = 'diff'
